services:
  postgres:
    image: postgres:17.2
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      
  server:
    container_name: server
    build: ./server
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:3001"
      - "5555:5555"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      IP_ADDRESS: ${IP_ADDRESS}
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
        - action: rebuild
          path: package.json
          target: /app
      
  client:
    container_name: client
    build: 
      context: ./client
      args:  
        REACT_APP_IP_ADDRESS: ${IP_ADDRESS}
    restart: always
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
        - action: rebuild
          path: package.json
          target: /app
      
  apache:
    container_name: apache-proxy
    build: 
      context: ./apache
      args:
        IP_ADDRESS: ${IP_ADDRESS}
    restart: always
    ports:
      - "80:80" 
      - "443:443" 
    env_file:
      - .env
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
    volumes:
      - ./certs:/etc/ssl/certs 
      - ./apache/reverse-proxy.conf:/usr/local/apache2/conf/extra/reverse-proxy.conf
    depends_on:
      - server
      - client
      
volumes:
  postgres: